### ISSUE TITLE
RunningAverageRssiFilter sampleExpiration modification ignored

### ISSUE THREAD

**Issue by fdiazgon** [AltBeacon/android-beacon-library-reference#30] opened 2017-05-24 17:06 UTC
Hi.

I'm trying to modify the time interval of the `RunningAverageRssiFilter` as explained here: [Adjusting the averaging time](https://altbeacon.github.io/android-beacon-library/distance_vs_time.html#adjusting-the-averaging-time). I'm calling both methods in my Application class (I've seen in the reference application that all the configuration is done in this class), however, the new value is ignored.

I've modified the `RunningAverageRssiFilter` class to log a message every time the method `setSampleExpirationMilliseconds` is called:

```java
public static void setSampleExpirationMilliseconds(long newSampleExpirationMilliseconds) {
        LogManager.d(TAG, "Changing sampleExpiration time to %d%n", newSampleExpirationMilliseconds);
        sampleExpirationMilliseconds = newSampleExpirationMilliseconds;
}
```

This method is called three times, as you can see in my Android Monitor:

![issue_abl](https://cloud.githubusercontent.com/assets/12219405/26415482/efe0dd0c-40b2-11e7-908b-bd0a767b58a8.png)

The first one corresponds to the call made from my Application class. I think the other two calls are made from the `RangedBeacon` constructor:

```java
public RangedBeacon(Beacon beacon) {
        //set RSSI filter
        try {
            Constructor cons = BeaconManager.getRssiFilterImplClass().getConstructors()[0];
            filter = (RssiFilter)cons.newInstance();
        } catch (Exception e) {
            LogManager.e(TAG, "Could not construct RssiFilterImplClass %s", BeaconManager.getRssiFilterImplClass().getName());
        }

        RunningAverageRssiFilter.setSampleExpirationMilliseconds(sampleExpirationMilliseconds);
        updateBeacon(beacon);
}
```

As a result, my configuration is ignored and `sampleExpirationMilliseconds` returns back to 20000. It seems that the `RangedBeacon` class has a static method to modify the time interval too. Should not this method be called as well? My current solution:

```java
long sampleExpirationMilliseconds = 5000L;
BeaconManager.setRssiFilterImplClass(RunningAverageRssiFilter.class);
RunningAverageRssiFilter.setSampleExpirationMilliseconds(sampleExpirationMilliseconds);
RangedBeacon.setSampleExpirationMilliseconds(sampleExpirationMilliseconds);
```

_Edited: sorry, I meant to add this issue in the android-beacon-library repository._

**Comment by fdiazgon** [comment] 2017-06-02 14:24
Please, @davidgyoung, check this issue

**Comment by davidgyoung** [comment] 2017-06-02 14:30
Apologies for the delay, @fdiazgon, let me take a look and see what I can find.

**Comment by davidgyoung** [comment] 2017-06-03 21:43
Reviewing this now, it appears that the documentation is currently wrong.  You are correct in your observations, you cannot use: `RunningAverageRssiFilter.setSampleExpirationMilliseconds(sampleExpirationMilliseconds);` to adjust this setting, because it is overridden by the call in `RangedBeacon`.  Currently, the proper way to set this setting is:

`RangedBeacon.setSampleExpirationMilliseconds(sampleExpirationMilliseconds);`

The change in #128 was intended to  shift this setting to the `RunningAverageRssiFilter`, which is why the documentation says to configure this way.  However, it appears it never worked as intended.   I will keep this issue open as I would like to change the code so that if the setter gets called on `RunningAverageRssiFilter` it takes precedence over what is called internally from `RangedBeacon`.  This will make the documentation correct and the API work as intended.

**Comment by davidgyoung** [comment] 2017-06-03 22:14
Fixed in https://github.com/AltBeacon/android-beacon-library/pull/523

**Closed by davidgyoung** 2017-06-03 22:14 UTC
